language: elixir

elixir:
  - 1.5
  - 1.4

otp_release:
  - 20.0
  - 19.3

services:
  - postgresql

env:
  global:
    - MIX_ENV=test
    - POSTGRES_USER="postgres"
    - POSTGRES_PASS=""

notifications:
  email: false

sudo: false

script:
  - mix test
